//
// Generated file, do not edit! Created by nedtool 5.4 from messages/get_headers_message.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __GET_HEADERS_MESSAGE_M_H
#define __GET_HEADERS_MESSAGE_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
    #include "pow_message_m.h"
// }}

/**
 * Class generated from <tt>messages/get_headers_message.msg:22</tt> by nedtool.
 * <pre>
 * message GetHeadersMessage extends POWMessage
 * {
 *     int64_t hash;
 * }
 * </pre>
 */
class GetHeadersMessage : public ::POWMessage
{
  protected:
    int64_t hash;

  private:
    void copy(const GetHeadersMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const GetHeadersMessage&);

  public:
    GetHeadersMessage(const char *name=nullptr, short kind=0);
    GetHeadersMessage(const GetHeadersMessage& other);
    virtual ~GetHeadersMessage();
    GetHeadersMessage& operator=(const GetHeadersMessage& other);
    virtual GetHeadersMessage *dup() const override {return new GetHeadersMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int64_t getHash() const;
    virtual void setHash(int64_t hash);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const GetHeadersMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, GetHeadersMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef __GET_HEADERS_MESSAGE_M_H

