//
// Generated file, do not edit! Created by nedtool 5.4 from messages/headers_message.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __HEADERS_MESSAGE_M_H
#define __HEADERS_MESSAGE_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
    #include "../blockchain/block.h"
    #include "pow_message_m.h"
    #include <vector>
    typedef std::vector<BlockHeader> HeadersVector;
// }}

/**
 * Class generated from <tt>messages/headers_message.msg:27</tt> by nedtool.
 * <pre>
 * message HeadersMessage extends POWMessage
 * {
 *     HeadersVector headers;
 * }
 * </pre>
 */
class HeadersMessage : public ::POWMessage
{
  protected:
    HeadersVector headers;

  private:
    void copy(const HeadersMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const HeadersMessage&);

  public:
    HeadersMessage(const char *name=nullptr, short kind=0);
    HeadersMessage(const HeadersMessage& other);
    virtual ~HeadersMessage();
    HeadersMessage& operator=(const HeadersMessage& other);
    virtual HeadersMessage *dup() const override {return new HeadersMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual HeadersVector& getHeaders();
    virtual const HeadersVector& getHeaders() const {return const_cast<HeadersMessage*>(this)->getHeaders();}
    virtual void setHeaders(const HeadersVector& headers);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const HeadersMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, HeadersMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef __HEADERS_MESSAGE_M_H

