//
// Generated file, do not edit! Created by nedtool 5.4 from messages/pow_message.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __POW_MESSAGE_M_H
#define __POW_MESSAGE_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>messages/pow_message.msg:16</tt> by nedtool.
 * <pre>
 * message POWMessage
 * {
 *     string command; // name of command to execute upon reaching destination 
 *     int source; // source node index of the sending node
 *     int versionNo;  // protocol version number of the message
 * }
 * </pre>
 */
class POWMessage : public ::omnetpp::cMessage
{
  protected:
    ::omnetpp::opp_string command;
    int source;
    int versionNo;

  private:
    void copy(const POWMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const POWMessage&);

  public:
    POWMessage(const char *name=nullptr, short kind=0);
    POWMessage(const POWMessage& other);
    virtual ~POWMessage();
    POWMessage& operator=(const POWMessage& other);
    virtual POWMessage *dup() const override {return new POWMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getCommand() const;
    virtual void setCommand(const char * command);
    virtual int getSource() const;
    virtual void setSource(int source);
    virtual int getVersionNo() const;
    virtual void setVersionNo(int versionNo);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const POWMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, POWMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef __POW_MESSAGE_M_H

