//
// Generated file, do not edit! Created by nedtool 5.4 from messages/scheduler_message.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __SCHEDULER_MESSAGE_M_H
#define __SCHEDULER_MESSAGE_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
    #include <vector>
    typedef std::vector<int> parametersVector;
// }}

/**
 * Class generated from <tt>messages/scheduler_message.msg:24</tt> by nedtool.
 * <pre>
 * message SchedulerMessage
 * {
 *     parametersVector parameters;
 *     string method;
 * }
 * </pre>
 */
class SchedulerMessage : public ::omnetpp::cMessage
{
  protected:
    parametersVector parameters;
    ::omnetpp::opp_string method;

  private:
    void copy(const SchedulerMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const SchedulerMessage&);

  public:
    SchedulerMessage(const char *name=nullptr, short kind=0);
    SchedulerMessage(const SchedulerMessage& other);
    virtual ~SchedulerMessage();
    SchedulerMessage& operator=(const SchedulerMessage& other);
    virtual SchedulerMessage *dup() const override {return new SchedulerMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual parametersVector& getParameters();
    virtual const parametersVector& getParameters() const {return const_cast<SchedulerMessage*>(this)->getParameters();}
    virtual void setParameters(const parametersVector& parameters);
    virtual const char * getMethod() const;
    virtual void setMethod(const char * method);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SchedulerMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SchedulerMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef __SCHEDULER_MESSAGE_M_H

