//
// Generated file, do not edit! Created by nedtool 5.4 from messages/version_message.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __VERSION_MESSAGE_M_H
#define __VERSION_MESSAGE_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
    #include "pow_message_m.h"
// }}

/**
 * Class generated from <tt>messages/version_message.msg:22</tt> by nedtool.
 * <pre>
 * message VersionMessage extends POWMessage
 * {
 *     int chainHeight;
 * }
 * </pre>
 */
class VersionMessage : public ::POWMessage
{
  protected:
    int chainHeight;

  private:
    void copy(const VersionMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const VersionMessage&);

  public:
    VersionMessage(const char *name=nullptr, short kind=0);
    VersionMessage(const VersionMessage& other);
    virtual ~VersionMessage();
    VersionMessage& operator=(const VersionMessage& other);
    virtual VersionMessage *dup() const override {return new VersionMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getChainHeight() const;
    virtual void setChainHeight(int chainHeight);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const VersionMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, VersionMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef __VERSION_MESSAGE_M_H

