//
// Generated file, do not edit! Created by nedtool 5.4 from p2p_msg.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __P2P_MSG_M_H
#define __P2P_MSG_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>p2p_msg.msg:1</tt> by nedtool.
 * <pre>
 * message P2P_Msg
 * {
 *     int source;
 *     int destination;
 *     int hopCount = 0;
 * }
 * </pre>
 */
class P2P_Msg : public ::omnetpp::cMessage
{
  protected:
    int source;
    int destination;
    int hopCount;

  private:
    void copy(const P2P_Msg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const P2P_Msg&);

  public:
    P2P_Msg(const char *name=nullptr, short kind=0);
    P2P_Msg(const P2P_Msg& other);
    virtual ~P2P_Msg();
    P2P_Msg& operator=(const P2P_Msg& other);
    virtual P2P_Msg *dup() const override {return new P2P_Msg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSource() const;
    virtual void setSource(int source);
    virtual int getDestination() const;
    virtual void setDestination(int destination);
    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const P2P_Msg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, P2P_Msg& obj) {obj.parsimUnpack(b);}


#endif // ifndef __P2P_MSG_M_H

